
name: "IntelRealSense"
config:
  class_dir: ""        # Directory where the class is located
  type: "Camera"
  frequency: 30        # default 30
  width: 640           # default 640
  height: 480          # default 480
  streams:
    depth:
      enable: True
      format: "z16"
    color:
      enable: True
      format: "bgr8"
    infrared:
      enable: True
      format: "y8"
  sim_config:
    visualize: True
    fov: 60                                    # default 60
    near_val: 0.1                              # default 0.1
    far_val: 100.0                             # default 100.0
    fix:
      camera_target_position: [0, 0, 0]
      distance: 0.75
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
      up_axis_index: 2
    attach:
      parent_name: "SimpleTwoWheelCar"
      parent_link: front_sensor_link
      offset_translation: [0.0, 0.0, 0.05]     # default [0, 0, 0]
      offset_rotation: [0.0, 0.0, 0.0]         # euler or quaternions, default [0, 0, 0]
      rel_camera_target: [1, 0, 0]             # default [1, 0, 0]      
